name: dartssh
version: 1.0.4+4
description: Dart SSH package providing First-class tunnelling primitives.
# author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/dartssh

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  asn1lib: ^1.0.0
  convert: ^3.0.0
  meta: ^1.1.6
  http: ^0.13.3
  # pedantic: ^1.8.0
  pointycastle: ^3.0.0
  # tweetnacl2: ^0.3.3
  validators: ^3.0.0
  pinenacl: ^0.3.3

dev_dependencies:
  build_runner: ^2.1.1
  test: ^1.6.5
